name: Documentation

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: ['**']
    paths-ignore:
      - 'docker/**'
      - 'website/**'
      - 'where_panel/**'
      - 'studio/**'
      - '.github/workflows/build_and_test.yml'
      - '.github/workflows/codeql.yml'
      - '.github/workflows/macos.yml'
      - '.github/workflows/pgxn.yml'
      - '.github/workflows/studio.yml'
      - '.github/workflows/wsl.yml'
      - 'release.sh'
      - 'CITATION.cff'
      - 'LICENSE'
      - 'META.json'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/pull_request_template.md'
  pull_request:
    paths-ignore:
      - 'docker/**'
      - 'website/**'
      - 'where_panel/**'
      - 'studio/**'
      - '.github/workflows/build_and_test.yml'
      - '.github/workflows/codeql.yml'
      - '.github/workflows/macos.yml'
      - '.github/workflows/pgxn.yml'
      - '.github/workflows/studio.yml'
      - '.github/workflows/wsl.yml'
      - 'release.sh'
      - 'CITATION.cff'
      - 'LICENSE'
      - 'META.json'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/pull_request_template.md'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    container: pgxn/pgxn-tools
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-tags: true
          fetch-depth: 0
      - run: apt update
      - run: apt -y install python3-breathe python3-sphinx-rtd-theme python3-sphinx-copybutton python3-pybtex python3-sphinxcontrib.bibtex graphviz wget postgresql-server-dev-all
      - run: |
          wget -q https://github.com/doxygen/doxygen/releases/download/Release_1_13_2/doxygen-1.13.2.linux.bin.tar.gz
          tar xzf doxygen-1.13.2.linux.bin.tar.gz
          cp doxygen-1.13.2/bin/doxygen /usr/local/bin/
      - run: make docs
