name: Documentation

on:
  push:
    paths-ignore:
      - 'docker/**'
      - 'website/**'
      - 'where_panel/**'
      - '.github/workflows/build_and_test.yml'
      - '.github/workflows/codeql.yml'
      - '.github/workflows/macos.yml'
      - '.github/workflows/wsl.yml'
  pull_request:
    paths-ignore:
      - 'docker/**'
      - 'website/**'
      - 'where_panel/**'
      - '.github/workflows/build_and_test.yml'
      - '.github/workflows/codeql.yml'
      - '.github/workflows/macos.yml'
      - '.github/workflows/wsl.yml'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    container: pgxn/pgxn-tools
    steps:
      - uses: actions/checkout@v6
      - run: apt update
      - run: apt -y install python3-breathe python3-sphinx-rtd-theme python3-pybtex python3-sphinxcontrib.bibtex graphviz wget
      - run: |
          wget -q https://github.com/doxygen/doxygen/releases/download/Release_1_13_2/doxygen-1.13.2.linux.bin.tar.gz
          tar xzf doxygen-1.13.2.linux.bin.tar.gz
          cp doxygen-1.13.2/bin/doxygen /usr/local/bin/
      - run: make docs
